export enum ClassId {
    NoClass = "class_none",
    Arcanist = "class_arcanist",
    Chimerist = "class_chimerist",
    Darkblade = "class_darkblade",
    Elementalist = "class_elementalist",
    Entropist = "class_Entropist",
    Fury = "class_fury",
    Guardian = "class_guardian",
    Loremaster = "class_loremaster",
    Orator = "class_orator",
    Rogue = "class_rogue",
    Sharpshooter = "class_sharpshooter",
    Spiritist = "class_spiritist",
    Tinkerer = "class_tinkerer",
    Wayfarer = "class_wayfarer",
    Weaponmaster = "class_weaponmaster",
}