export enum WeaponId {
  Staff = "wpn_staff",
  Tome = "wpn_tome",
  Crossbow = "wpn_crossbow",
  Shortbow = "wpn_shortbow",
  Unarmed = "wpn_unarmed",
  ImprovisedMelee = "wpn_improv_melee",
  IronKnuckle = "wpn_knuckle",
  Dagger = "wpn_dagger",
  Pistol = "wpn_pistol",
  ChainWhip = "wpn_whip",
  IronHammer = "wpn_hammer",
  BroadAxe = "wpn_broadaxe",
  WarAxe = "wpn_waraxe",
  LightSpear = "wpn_lightspear",
  HeavySpear = "wpn_heavyspear",
  BronzeSword = "wpn_sword",
  Greatsword = "wpn_greatsword",
  Katana = "wpn_katana",
  Rapier = "wpn_rapier",
  ImprovisedRanged = "wpn_improv_ranged",
  Shuriken = "wpn_shuriken",
}